import type { ProductSummary, Category } from "@/types";

const IMG = {
  absoluteBlack:
    "https://lh3.googleusercontent.com/aida-public/AB6AXuAlIgJRhbxAKqMijDIu5rkuzslBm4VyjNRvjRymvBLU3pz0WrLlYCYgBtMMEy5lPXptqIgFZtP4ZZzHOxnThTKH29IlRrQeG0kzMf8Cb0M8j_Gq3rNwabXqGYNIYoIfhqeNy6el_gXFz15N429zLWgwdFzInz5Qh1eGeXqncR4Mzmp5or7zuSJECkv18zILPw2iTyxIVDcXWCMizPO6kt771QwpuPwTiOdflztv1MAKN01OpGpot0pCI8rP1GmFliKhzTBcIAtGAlfj",
  marble:
    "https://lh3.googleusercontent.com/aida-public/AB6AXuDjeQSN_pQYp-raOPTfLGmkRrsBntkgrraR995BmZSzsvwNWFA-9d7yRfqz3wn6I1vnvoCCxNgSFWyJ01DS3fAInBMt5EkMLamB4jx5OfpG7wK8OKoLaagQcpcesQHCYsa6SXuMQHbtZPY7JB6PMeu9JfxhQo9hsDbBh5i0d5AbBPdvLNC2A1BAAXEIqz3AtiM4MTzx83F_I55z1hg4Fp92JlzuQp4moz4WAhj-IdozEKrA7E3lpMBh3r2hEP8ALJSEAY4EOD87UDpb",
  tiles:
    "https://lh3.googleusercontent.com/aida-public/AB6AXuB5hkcytrl-wZhEDxlc1xevakHj2iaZaZ9ONiJrB8mYB2wvh7lZa0vcS1eE_W_YChMLxgapspcuxmnuYPasdO6w8z3McVUQ_5DiLOvWdsY1SLUlyu-vfzrCOcA74veEs76N5_9_zQBPWjKbMEU4ZVnqvFz_GO6mfeYnlbg-K70i8ac0v9c7ss9-nUfUJSJzvVAlR0GdKbZa32HVcfe5zFHwd3XAw-4wHdr5MhYyjP1i_th1290ZNF7LhjP1j4eyQcZ8DHu0OMVC-8vz",
  quartz:
    "https://lh3.googleusercontent.com/aida-public/AB6AXuDWADQJ93A_02JzVzfXairNl2k3sBWCR-OF25CkoQi8YaZyERa3jl5IcHuYJQfFS-TiRWBl_spJlBoVtZswWEWewiyzKNAQiZKEvtpbnHBp1GeJZBojFNnf_Y8oU1Hbn0jeK1DqCKTGozxUw475YWG0-y8rVIH9Ed17UAQhhZh5i4qxL8O4uXI7t4y6Xu0YdOj2ouWZEQ5yj9jKB-oU2rF9cWPE5jy2earABliIETnc6T_QAGcEkLzIQ-cnDWvxYn9R4msTReviQnZo",
  sandstone:
    "https://lh3.googleusercontent.com/aida-public/AB6AXuBoXdMRFWWdJnULQ_TXmGh2TVcepmAHvF_eB9_047fjgCnsUI4fVe0y4ISpTrqL3JGBZlEwkal9RYuD-plObgw-CzgiabgrytCVPhMvOf00quAX9V-w15Zr_c-20YA6fTLQWEdyQS0ihczVjwp4Fck7q0xpzI2iZHgcBAuM0YQuKjO2hypZMaFU9G4duZxSLlDWpQejONNO6w9h-b3vdP5k3zroc0Ae5nrcJO3pPfxqb3sSdOg7dLBvEqV8yAaz7DBKAZqpFXEEaNjJ",
  limestone:
    "https://lh3.googleusercontent.com/aida-public/AB6AXuDHHC7SLX_Jqp3XHymLdewJ8kDVyo2ZQYnD8Mp6VKczqGcPsUpPvm-bE7ps6UNOhapsZ6UUrdiEYPHD51r6Zb9fZwqiJ_UKFak-gmQc33qmd_4GxnDrc4S5NK9z-RxesLz0v1p4Jgc0hiE7BWvqHInSX8o2_TMgqN3UFUI_9BnQotaDcND50vSIhyBtDVHk7idDg9gHJ7ka7xBWdn7SZujRwyf7NTuoCiFTCxWXVWLMKSPeflQp6ioKIaqr_ZK_zqH5sdn6tYrcPVAp",
  slatestone:
    "https://lh3.googleusercontent.com/aida-public/AB6AXuAp49VmZPdLRgHIqsOWIaRoRRMQ406jSBZiLLBA8mgML1N2e0epW9munvCjCUk5ArptJy125mmQvtG7D69Jal5tMg0PF_q-k97e70L9yuNb32YclpM74MdoyZVO-Czh8Q_Ig5QdCQT1IkqQ9-yuR9zqY5MDnM-ZdrizKz_76ZNyWkybOB3_03_yZz4ImR6wTz0S1VSZrZyIxx6Jlc4FfATfl1NYJUteOhuKfp3KdVLPtEaOD6BPWA6KkAAalkc396vIfianIvE8ampw",
  quartziteNatural:
    "https://lh3.googleusercontent.com/aida-public/AB6AXuC3wfKsRnyUwuCsV9tcnO8Ap0Gmcyya0_2Fy-CVXO3HDWEym8jkMWbaVNyEfVJ0Wpcfo3dJksYt6j055hXothBgB7HY-fli63n9UUqwUddit9MBtU1JKe_fe6StUbHaZ1XFsIjU095855BZ2zCtn9XcXknn4n2tTJg3ffHN8kmrt69LAGBrceqaDqFnInYMQN7UDi1cp2S3nyDimN3HmXq8FQp44EQOt-yG1SPi0rQ3QnbnftpHtrr7zt9N9nQ6o-PxYYIpI0J_W7Bf",
  pebbles:
    "https://lh3.googleusercontent.com/aida-public/AB6AXuC-ZveG7RI4m7vmnEEcJRuHckPIr7q6r2gRuax5NJheW5ZHWsksBGVNhu4cxKhLVB7ovL9vapFUNhpW_DXn8-5-liGdFrM28ju3kQpuhWr-NHObA9qOqQXKCebVhhtbMhHVutb1gWBAQi6TOwAxQJSLEbjJgm1BviLWhVApjuoF9Zx6-m--d2xwse-Lmbb30ynNDQqklc1RyU-yUodKcy-fMLoIiVKG0SF2ViVxgtxiFy3y-U8tLsFh0uLHFgrq23DA17At5_6GdrMQ",
  panels:
    "https://lh3.googleusercontent.com/aida-public/AB6AXuAh2f1dIiZdtOy15POc1ZxLpwu69j_OnGJcbG2lrlyDu4EAqnfsYJq1U8qaE4oVXdQRE3rvf8UOEmJzfp9axbops62Biu6ZfCymWEo1zwg8Tah4QXeJw6Sy5YcJCu3U9kCr30H5WaSoqBHu2WkxhByhTbDOUmF4Fh7CC1Gcm8-sk6eF8EYecsOa5r0znbCHUFLnt4NEQ6tOOAxvlO_aiBGSalRDKrbplYkoETXPhdPgzLuPrpbckWBNk_k8udfzYxcuE8bG6FcVvfxZ",
  whiteMarble:
    "https://lh3.googleusercontent.com/aida-public/AB6AXuDHHC7SLX_Jqp3XHymLdewJ8kDVyo2ZQYnD8Mp6VKczqGcPsUpPvm-bE7ps6UNOhapsZ6UUrdiEYPHD51r6Zb9fZwqiJ_UKFak-gmQc33qmd_4GxnDrc4S5NK9z-RxesLz0v1p4Jgc0hiE7BWvqHInSX8o2_TMgqN3UFUI_9BnQotaDcND50vSIhyBtDVHk7idDg9gHJ7ka7xBWdn7SZujRwyf7NTuoCiFTCxWXVWLMKSPeflQp6ioKIaqr_ZK_zqH5sdn6tYrcPVAp",
};

export const PLACEHOLDER_CATEGORIES: Category[] = [
  { _id: "cat-granite", title: "Granite", slug: { current: "granite" }, description: "Igneous rock, 6–7 Mohs hardness", order: 1 },
  { _id: "cat-marble", title: "Marble", slug: { current: "marble" }, description: "Metamorphic, luminous veining", order: 2 },
  { _id: "cat-sandstone", title: "Sandstone", slug: { current: "sandstone" }, description: "Sedimentary, warm earth tones", order: 3 },
  { _id: "cat-limestone", title: "Limestone", slug: { current: "limestone" }, description: "Soft elegance, classic warmth", order: 4 },
  { _id: "cat-tiles", title: "Tiles", slug: { current: "tiles" }, description: "Vitrified · Porcelain · Wall · Digital", order: 5 },
  { _id: "cat-quartz", title: "Quartz", slug: { current: "quartz" }, description: "Engineered stone, zero maintenance", order: 6 },
  { _id: "cat-slatestone", title: "Slatestone", slug: { current: "slatestone" }, description: "Foliated, natural cleft surface", order: 7 },
  { _id: "cat-quartzite", title: "Quartzite", slug: { current: "quartzite" }, description: "Natural quartz, extreme hardness", order: 8 },
];

export interface PlaceholderProduct extends Omit<ProductSummary, "images"> {
  imageUrl: string;
  images: [];
}

export const PLACEHOLDER_PRODUCTS: PlaceholderProduct[] = [
  // ── Granite ──────────────────────────────────────────────
  {
    _id: "p-absolute-black",
    title: "Absolute Black Granite",
    slug: { current: "absolute-black-granite" },
    featured: true,
    inStock: true,
    origin: "Karnataka, India",
    color: "Black",
    finish: ["Polished", "Honed", "Flamed", "Leather"],
    applications: ["Kitchen Countertops", "Flooring", "Wall Cladding"],
    availableSizes: ["240×120 cm", "300×180 cm", "60×60 cm"],
    images: [],
    imageUrl: IMG.absoluteBlack,
    category: { _id: "cat-granite", title: "Granite", slug: { current: "granite" } },
  },
  {
    _id: "p-tan-brown",
    title: "Tan Brown Granite",
    slug: { current: "tan-brown-granite" },
    featured: false,
    inStock: true,
    origin: "Andhra Pradesh, India",
    color: "Brown",
    finish: ["Polished", "Honed", "Leather"],
    applications: ["Countertops", "Flooring", "Staircases"],
    availableSizes: ["240×120 cm", "300×180 cm"],
    images: [],
    imageUrl: IMG.quartziteNatural,
    category: { _id: "cat-granite", title: "Granite", slug: { current: "granite" } },
  },
  {
    _id: "p-kashmir-white",
    title: "Kashmir White Granite",
    slug: { current: "kashmir-white-granite" },
    featured: true,
    inStock: true,
    origin: "Tamil Nadu, India",
    color: "White",
    finish: ["Polished", "Honed"],
    applications: ["Kitchen Countertops", "Bathroom Vanities", "Flooring"],
    availableSizes: ["240×120 cm", "300×200 cm", "60×60 cm"],
    images: [],
    imageUrl: IMG.whiteMarble,
    category: { _id: "cat-granite", title: "Granite", slug: { current: "granite" } },
  },
  {
    _id: "p-steel-grey",
    title: "Steel Grey Granite",
    slug: { current: "steel-grey-granite" },
    featured: false,
    inStock: true,
    origin: "Andhra Pradesh, India",
    color: "Grey",
    finish: ["Polished", "Flamed", "Bush-hammered"],
    applications: ["Exterior Cladding", "Flooring", "Countertops"],
    availableSizes: ["240×120 cm", "300×180 cm"],
    images: [],
    imageUrl: IMG.slatestone,
    category: { _id: "cat-granite", title: "Granite", slug: { current: "granite" } },
  },
  {
    _id: "p-galaxy-black",
    title: "Black Galaxy Granite",
    slug: { current: "black-galaxy-granite" },
    featured: true,
    inStock: false,
    origin: "Andhra Pradesh, India",
    color: "Black",
    finish: ["Polished", "Honed"],
    applications: ["Countertops", "Feature Walls", "Fireplace Surrounds"],
    availableSizes: ["240×120 cm", "300×180 cm", "60×30 cm"],
    images: [],
    imageUrl: IMG.absoluteBlack,
    category: { _id: "cat-granite", title: "Granite", slug: { current: "granite" } },
  },

  // ── Marble ───────────────────────────────────────────────
  {
    _id: "p-makrana-white",
    title: "Makrana White Marble",
    slug: { current: "makrana-white-marble" },
    featured: true,
    inStock: true,
    origin: "Rajasthan, India",
    color: "White",
    finish: ["Polished", "Honed"],
    applications: ["Flooring", "Wall Cladding", "Temple Architecture"],
    availableSizes: ["240×120 cm", "300×180 cm", "60×60 cm"],
    images: [],
    imageUrl: IMG.whiteMarble,
    category: { _id: "cat-marble", title: "Marble", slug: { current: "marble" } },
  },
  {
    _id: "p-portoro-gold",
    title: "Portoro Gold Marble",
    slug: { current: "portoro-gold-marble" },
    featured: true,
    inStock: true,
    origin: "Rajasthan, India",
    color: "Black",
    finish: ["Polished", "Honed", "Antiqued"],
    applications: ["Luxury Interiors", "Feature Walls", "Reception Areas"],
    availableSizes: ["240×120 cm", "300×180 cm"],
    images: [],
    imageUrl: IMG.marble,
    category: { _id: "cat-marble", title: "Marble", slug: { current: "marble" } },
  },
  {
    _id: "p-indian-green",
    title: "Indian Green Marble",
    slug: { current: "indian-green-marble" },
    featured: false,
    inStock: true,
    origin: "Rajasthan, India",
    color: "Green",
    finish: ["Polished", "Honed", "Sandblasted"],
    applications: ["Flooring", "Wall Cladding", "Decorative Panels"],
    availableSizes: ["240×120 cm", "60×60 cm", "30×30 cm"],
    images: [],
    imageUrl: IMG.slatestone,
    category: { _id: "cat-marble", title: "Marble", slug: { current: "marble" } },
  },
  {
    _id: "p-rainforest-brown",
    title: "Rainforest Brown Marble",
    slug: { current: "rainforest-brown-marble" },
    featured: false,
    inStock: true,
    origin: "Rajasthan, India",
    color: "Brown",
    finish: ["Polished", "Honed"],
    applications: ["Countertops", "Feature Walls", "Bathroom Vanities"],
    availableSizes: ["240×120 cm", "300×180 cm"],
    images: [],
    imageUrl: IMG.sandstone,
    category: { _id: "cat-marble", title: "Marble", slug: { current: "marble" } },
  },
  {
    _id: "p-fantasy-brown",
    title: "Fantasy Brown Marble",
    slug: { current: "fantasy-brown-marble" },
    featured: false,
    inStock: true,
    origin: "Rajasthan, India",
    color: "Multicolor",
    finish: ["Polished", "Honed", "Leather"],
    applications: ["Kitchen Islands", "Backsplashes", "Bathroom Walls"],
    availableSizes: ["240×120 cm", "300×200 cm"],
    images: [],
    imageUrl: IMG.quartziteNatural,
    category: { _id: "cat-marble", title: "Marble", slug: { current: "marble" } },
  },

  // ── Sandstone ────────────────────────────────────────────
  {
    _id: "p-teak-sandstone",
    title: "Teak Sandstone",
    slug: { current: "teak-sandstone" },
    featured: true,
    inStock: true,
    origin: "Rajasthan, India",
    color: "Brown",
    finish: ["Natural Split", "Honed", "Sandblasted"],
    applications: ["Exterior Cladding", "Garden Landscaping", "Paving"],
    availableSizes: ["60×60 cm", "60×30 cm", "Random"],
    images: [],
    imageUrl: IMG.sandstone,
    category: { _id: "cat-sandstone", title: "Sandstone", slug: { current: "sandstone" } },
  },
  {
    _id: "p-rainbow-sandstone",
    title: "Rainbow Sandstone",
    slug: { current: "rainbow-sandstone" },
    featured: false,
    inStock: true,
    origin: "Rajasthan, India",
    color: "Multicolor",
    finish: ["Natural Split", "Honed"],
    applications: ["Exterior Cladding", "Landscaping", "Pool Surrounds"],
    availableSizes: ["60×60 cm", "60×30 cm", "Random"],
    images: [],
    imageUrl: IMG.panels,
    category: { _id: "cat-sandstone", title: "Sandstone", slug: { current: "sandstone" } },
  },
  {
    _id: "p-mint-sandstone",
    title: "Mint Sandstone",
    slug: { current: "mint-sandstone" },
    featured: false,
    inStock: true,
    origin: "Rajasthan, India",
    color: "Green",
    finish: ["Natural Split", "Honed", "Brushed"],
    applications: ["Flooring", "Wall Cladding", "Pathways"],
    availableSizes: ["60×90 cm", "60×30 cm", "30×30 cm"],
    images: [],
    imageUrl: IMG.limestone,
    category: { _id: "cat-sandstone", title: "Sandstone", slug: { current: "sandstone" } },
  },

  // ── Limestone ────────────────────────────────────────────
  {
    _id: "p-kota-blue",
    title: "Kota Blue Limestone",
    slug: { current: "kota-blue-limestone" },
    featured: true,
    inStock: true,
    origin: "Rajasthan, India",
    color: "Blue",
    finish: ["Honed", "Natural", "Polished"],
    applications: ["Flooring", "Pathways", "Pool Decks"],
    availableSizes: ["60×60 cm", "60×30 cm", "30×30 cm"],
    images: [],
    imageUrl: IMG.limestone,
    category: { _id: "cat-limestone", title: "Limestone", slug: { current: "limestone" } },
  },
  {
    _id: "p-jaisalmer-yellow",
    title: "Jaisalmer Yellow Limestone",
    slug: { current: "jaisalmer-yellow-limestone" },
    featured: false,
    inStock: true,
    origin: "Rajasthan, India",
    color: "Yellow",
    finish: ["Honed", "Natural Split", "Polished"],
    applications: ["Exterior Cladding", "Flooring", "Feature Walls"],
    availableSizes: ["60×60 cm", "60×30 cm", "Random"],
    images: [],
    imageUrl: IMG.sandstone,
    category: { _id: "cat-limestone", title: "Limestone", slug: { current: "limestone" } },
  },

  // ── Tiles ────────────────────────────────────────────────
  {
    _id: "p-statuario-vitrified",
    title: "Statuario Look Vitrified Tile",
    slug: { current: "statuario-vitrified-tile" },
    featured: true,
    inStock: true,
    origin: "Gujarat, India",
    color: "White",
    finish: ["Glossy", "Matt", "Carving"],
    applications: ["Living Room Flooring", "Lobby", "Commercial Spaces"],
    availableSizes: ["60×120 cm", "80×80 cm", "120×120 cm", "120×240 cm"],
    images: [],
    imageUrl: IMG.tiles,
    category: { _id: "cat-tiles", title: "Tiles", slug: { current: "tiles" } },
  },
  {
    _id: "p-onyx-porcelain",
    title: "Onyx Design Porcelain Tile",
    slug: { current: "onyx-design-porcelain-tile" },
    featured: false,
    inStock: true,
    origin: "Gujarat, India",
    color: "Beige",
    finish: ["Glossy", "Matt"],
    applications: ["Bathroom Walls", "Feature Walls", "Flooring"],
    availableSizes: ["60×120 cm", "80×160 cm"],
    images: [],
    imageUrl: IMG.whiteMarble,
    category: { _id: "cat-tiles", title: "Tiles", slug: { current: "tiles" } },
  },
  {
    _id: "p-wood-plank-digital",
    title: "Wood Plank Digital Tile",
    slug: { current: "wood-plank-digital-tile" },
    featured: false,
    inStock: true,
    origin: "Gujarat, India",
    color: "Brown",
    finish: ["Matt", "Rustic", "Sugar"],
    applications: ["Bedroom Flooring", "Living Room", "Outdoor Decks"],
    availableSizes: ["20×120 cm", "20×100 cm", "60×120 cm"],
    images: [],
    imageUrl: IMG.panels,
    category: { _id: "cat-tiles", title: "Tiles", slug: { current: "tiles" } },
  },
  {
    _id: "p-concrete-effect-wall",
    title: "Concrete Effect Wall Tile",
    slug: { current: "concrete-effect-wall-tile" },
    featured: false,
    inStock: true,
    origin: "Gujarat, India",
    color: "Grey",
    finish: ["Matt", "Rustic"],
    applications: ["Kitchen Backsplash", "Bathroom Walls", "Commercial Walls"],
    availableSizes: ["30×60 cm", "30×45 cm", "25×75 cm"],
    images: [],
    imageUrl: IMG.slatestone,
    category: { _id: "cat-tiles", title: "Tiles", slug: { current: "tiles" } },
  },
  {
    _id: "p-calacatta-pgvt",
    title: "Calacatta Gold PGVT Tile",
    slug: { current: "calacatta-gold-pgvt-tile" },
    featured: true,
    inStock: true,
    origin: "Gujarat, India",
    color: "White",
    finish: ["Glossy", "Satin"],
    applications: ["Living Room", "Hotel Lobbies", "Luxury Bathrooms"],
    availableSizes: ["80×160 cm", "120×240 cm"],
    images: [],
    imageUrl: IMG.marble,
    category: { _id: "cat-tiles", title: "Tiles", slug: { current: "tiles" } },
  },

  // ── Quartz (Engineered) ──────────────────────────────────
  {
    _id: "p-calacatta-quartz",
    title: "Calacatta Gold Quartz",
    slug: { current: "calacatta-gold-quartz" },
    featured: true,
    inStock: true,
    origin: "Engineered",
    color: "White",
    finish: ["Polished", "Honed"],
    applications: ["Kitchen Countertops", "Bathroom Vanities", "Islands"],
    availableSizes: ["300×140 cm", "320×160 cm"],
    images: [],
    imageUrl: IMG.quartz,
    category: { _id: "cat-quartz", title: "Quartz", slug: { current: "quartz" } },
  },
  {
    _id: "p-midnight-black-quartz",
    title: "Midnight Black Quartz",
    slug: { current: "midnight-black-quartz" },
    featured: false,
    inStock: true,
    origin: "Engineered",
    color: "Black",
    finish: ["Polished", "Leather"],
    applications: ["Countertops", "Bar Tops", "Fireplace Surrounds"],
    availableSizes: ["300×140 cm", "300×160 cm"],
    images: [],
    imageUrl: IMG.absoluteBlack,
    category: { _id: "cat-quartz", title: "Quartz", slug: { current: "quartz" } },
  },
  {
    _id: "p-concrete-grey-quartz",
    title: "Concrete Grey Quartz",
    slug: { current: "concrete-grey-quartz" },
    featured: false,
    inStock: true,
    origin: "Engineered",
    color: "Grey",
    finish: ["Honed", "Textured"],
    applications: ["Kitchen Countertops", "Commercial Surfaces"],
    availableSizes: ["300×140 cm", "320×160 cm"],
    images: [],
    imageUrl: IMG.pebbles,
    category: { _id: "cat-quartz", title: "Quartz", slug: { current: "quartz" } },
  },

  // ── Slatestone ───────────────────────────────────────────
  {
    _id: "p-black-slate",
    title: "Black Slate",
    slug: { current: "black-slate" },
    featured: false,
    inStock: true,
    origin: "Andhra Pradesh, India",
    color: "Black",
    finish: ["Natural Split", "Honed", "Calibrated"],
    applications: ["Roofing", "Flooring", "Wall Cladding"],
    availableSizes: ["60×30 cm", "30×30 cm", "Random"],
    images: [],
    imageUrl: IMG.slatestone,
    category: { _id: "cat-slatestone", title: "Slatestone", slug: { current: "slatestone" } },
  },
  {
    _id: "p-rusty-slate",
    title: "Rusty Slate",
    slug: { current: "rusty-slate" },
    featured: true,
    inStock: true,
    origin: "Rajasthan, India",
    color: "Multicolor",
    finish: ["Natural Split", "Calibrated"],
    applications: ["Feature Walls", "Exterior Cladding", "Landscape"],
    availableSizes: ["60×30 cm", "30×15 cm", "Random"],
    images: [],
    imageUrl: IMG.panels,
    category: { _id: "cat-slatestone", title: "Slatestone", slug: { current: "slatestone" } },
  },

  // ── Quartzite (Natural) ──────────────────────────────────
  {
    _id: "p-silver-quartzite",
    title: "Silver Quartzite",
    slug: { current: "silver-quartzite" },
    featured: false,
    inStock: true,
    origin: "Rajasthan, India",
    color: "Grey",
    finish: ["Honed", "Natural Split", "Leathered"],
    applications: ["Countertops", "Flooring", "Exterior Cladding"],
    availableSizes: ["240×120 cm", "300×180 cm"],
    images: [],
    imageUrl: IMG.quartziteNatural,
    category: { _id: "cat-quartzite", title: "Quartzite", slug: { current: "quartzite" } },
  },
  {
    _id: "p-golden-quartzite",
    title: "Golden Quartzite",
    slug: { current: "golden-quartzite" },
    featured: true,
    inStock: true,
    origin: "Rajasthan, India",
    color: "Yellow",
    finish: ["Honed", "Natural Split", "Polished"],
    applications: ["Feature Walls", "Flooring", "Outdoor Areas"],
    availableSizes: ["60×30 cm", "30×30 cm", "Random"],
    images: [],
    imageUrl: IMG.sandstone,
    category: { _id: "cat-quartzite", title: "Quartzite", slug: { current: "quartzite" } },
  },
];
